// <auto-generated />
namespace GerenciadorDePedidos.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class Carga8 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Carga8));
        
        string IMigrationMetadata.Id
        {
            get { return "201512201258119_Carga8"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
